//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System_Simple.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class book
    {
        public int id { get; set; }

        [DisplayName("Book Name")]
        public string bname { get; set; }

        [DisplayName("Category ID")]
        public Nullable<int> cat_id { get; set; }

        [DisplayName("Author ID")]
        public Nullable<int> a_id { get; set; }

        [DisplayName("Publisher ID")]
        public Nullable<int> p_id { get; set; }

        [DisplayName("Contents")]
        public string contents { get; set; }
        public Nullable<int> pages { get; set; }

        [DisplayName("Edition")]
        public string edition { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
